### ISSUE TITLE
[Win]TNB_Version_31 Particular Time Later this msg shows Continues

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Account-Manager#523] opened 2020-11-30 05:49 UTC
**Bug Description**
5-10 min later Continuously Display This msg

**Steps to Reproduce**
1. Install TNB Application 1.0.0-alpha.31
2. Manually Enter IP Address This 54.193.31.159
3. See the right side top corner this msg "An Error Occurred When Getting Clean Status"

**Expected behavior**
msg not showing continuously

**Actual behavior**
this msg shows "An Error Occurred When Getting Clean Status"

**Screenshots/Recordings**
https://prnt.sc/vskm9r 

**OS and Browser**
 - OS: Windows 10

**Comment by angle943** [comment] 2021-01-24 16:45
closing for now, as i can't reproduce

**Closed by angle943** 2021-01-24 16:45 UTC
Labels: bug
