### ISSUE TITLE
[MAC] Error message displayed while sending points

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Account-Manager#398] opened 2020-10-09 12:38 UTC
**Bug Description**
Error message displayed while sending points

**Steps to Reproduce**
1. Go to 'Friend's account"
2. See error

**Expected behavior**
Point should be sent without error

**Actual behavior**
Error message displayed while sending points

**Screenshots/Recordings**
https://recordit.co/iHItx3hv2w

**OS and Browser**
 - OS: [MAC Notebook pro]

**Additional context**
App version 22

**Account Number**
15e164325715c9552911caf7e3ea1759f4c2ccba5fd82864a4d811d67935c4f9

**Comment by mayinghan** [comment] 2020-10-19 03:40
Does this issue still exist? I cant reproduce it in my local env.

**Comment by webdeveloperswj** [comment] 2020-10-20 04:51
@mayinghan Rechecked again issue not reproducible

**Comment by angle943** [comment] 2020-10-22 02:36
we'll close it for now then, and reopen if it pops up again

**Closed by angle943** 2020-10-22 02:36 UTC
Labels: 5000, bug
