### ISSUE TITLE
Notifications not working

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Account-Manager#390] opened 2020-10-07 12:58 UTC
Notification was working when app is installed after certain time it stopped working 
http://recordit.co/rVeyiwk1Ou

**Comment by brian316** [comment] 2020-10-13 18:04
How much time passed? Is it reproducible?

**Comment by brian316** [comment] 2020-10-13 18:28
I noticed from the video in the link that the account balance did not update after the transaction was made. After you did a refresh the balance didn't even show. I'm wondering if the transaction ever took place?

**Comment by buckyroberts** [comment] 2020-10-16 03:09
Was due to a CV error, should be fixed now.

**Closed by buckyroberts** 2020-10-16 03:09 UTC
Labels: 5000, bug, engineering
